### ISSUE TITLE
Reward problem in the scene of Crawler

### ISSUE THREAD

**Issue by lyy0095** [HernandezEduin/Trained-ML-Agents-Actors#1]
Thanks for the paper of <PPO or SAC: A comparison between algorithms Progress Report>, this is great!

But as shown in Fig.1, the Cumulative Reward of Crawler may nearly to 3000 when Episode Length come to 1000, but in the script “Project/Assets/ML-Agents/Examples/Crawler/Scripts/CrawlerAgent.cs” of ML-Agent Toolkit，the only _AddReward()_ function was limited to [0, 1] (TouchedTarget() is never used in the whole script), so the biggest reward will be 1000.

Considering that you have trained the scene of Crawler, could you please to explain how can we got the reward 3000?
Thank you for your reply!

**Comment by HernandezEduin** [comment]
Unfortunately, I'm unable to provide a clear answer. According to [#5768](https://github.com/Unity-Technologies/ml-agents/pull/5768), the function TouchTarget() goes unused. It might be called via UI instead of via code.

**Comment by HernandezEduin** [comment]
Oh yeah, I remember one important aspect: you are training multiple models simultaneously. So the rewards is also an accumulation from their result, not a single agent (see the image below). That's the whole point of using PPO and SAC algorithms: training multiple agents simultaneously. Hope this solves your question~

![image](https://github.com/user-attachments/assets/ef2080d5-5e05-42da-9223-5819b91eeffa)

**Comment by lyy0095** [comment]
Thank you very much for your reply!
Great!
This answer solves my problems,  because I did not notice the cumulative issue of many different scenes.
